<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    <PackageReference Include="Swashbuckle.AspNetCore"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DigitalNotes.Application\DigitalNotes.Application.csproj" />
    <ProjectReference Include="..\DigitalNotes.ServiceDefaults\DigitalNotes.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
