<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>1ffa2986-c202-40d3-abf7-4ed2f7dd63ab</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="9.0.0"/>
        <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DigitalNotes.API\DigitalNotes.API.csproj" />
      <ProjectReference Include="..\DigitalNotes.MigrationService\DigitalNotes.MigrationService.csproj" />
      <ProjectReference Include="..\DigitalNotes.Identity\DigitalNotes.Identity.csproj" />
    </ItemGroup>

</Project>
